// /services/rigging — the pillar. Rigging is the business; this page names every kind of it.
module.exports = {
  slug: 'rigging',
  cardBlurb: 'Engineered lifts, machine setting, and heavy moves — from a few hundred pounds to 200,000 lbs and beyond.',
  title: 'Industrial Rigging Company | Rigging Services Nationwide | Badass Logistics',
  description: 'Industrial rigging company with crews across 88 metros — machinery moving, factory relocation, MRI, crane lifts, jacking and skidding, and millwright work.',
  serviceType: 'Industrial Rigging',
  hero: '/assets/img/rigging-hero.jpg',
  band: '/assets/img/rigging-crane2.jpg',
  bandAnnots: ['BOOM 100 FT', 'PICK &amp; SET ✓'],
  tag: 'riggers first — every kind of rigging',
  h1: 'Industrial <span class="y">Rigging Services</span>',
  lead: 'When it\'s too heavy, too tight, or too expensive to get wrong, you call a rigger. We plan every pick like an engineering problem and run it like a road crew — machinery moving, plant relocation, MRI rigging, crane lifts, jacking and skidding, and millwright work. From a few hundred pounds to 200,000 lbs and beyond.',
  cta: 'Request a Rigging Quote',
  cta2: { href: '#types', label: 'Every Type of Rigging' },
  annots: ['⌀ 60-TON LIFT', 'SWL <span class="lbl">safe working load</span>90,000 LBS', 'RADIUS 42 FT', 'C.G. ✓ center of gravity'],
  bgnotes: ['LIFT PLAN SIGNED', 'SLING ANGLE 60°', 'FLOOR PSI ✓', 'TAGLINES ON', 'PATH OF TRAVEL ✓', 'SET &amp; LEVEL', 'GANTRY 4-LEG', 'TOE JACK UNDER', 'SPOTTER — SIGNAL', 'RIGGED TO OEM', 'WLL CHECKED ✓', 'ONE CREW'],
  quickAnswer: 'Industrial rigging is the planning and hands-on work of lifting, moving, and setting heavy equipment — machines, production lines, MRI scanners, transformers, chillers — often through tight doorways or onto elevated pads. Badass Logistics is a rigging company first: our own crews and rigging gear handle every kind of rigging nationwide, from a single machine to a full plant, set and leveled to spec.',
  intro: {
    h2: 'Every kind of rigging, one accountable crew',
    paragraphs: [
      'Rigging is not one job. Setting a 40,000-lb press on a new foundation, skating a CT scanner down a hospital corridor, craning a chiller onto a roof, and tearing out a production line are four different problems with four different gear lists. What they share is the part that matters: somebody has to measure the load, find the center of gravity, check the floor, and plan the pick before anything leaves the ground.',
      'That\'s the work Badass Logistics is built around. We own the rigging side — the crews, the jacks, skates, gantries and slings, and the planning — and we run it the same way on every job: survey first, documented lift plan, controlled execution, then set, level, and sign off. One crew from the first measurement to the final shim, so nothing falls into the gap between a rigger, a millwright, and whoever was supposed to move it next.',
      'When a rigged machine has to travel to another building, another city, or another state, we don\'t hand you off. We manage it as <a href="/services/project-freight">project freight</a> — crated, loaded, and moved through our licensed broker and carrier partners inside the same project plan — and our crew is waiting at the other end to set it.',
    ],
  },
  capabilities: {
    tag: 'what rigging covers',
    h2: 'What our riggers do',
    items: [
      { k: 'machine setting', h: 'Set, Anchor &amp; Level', p: 'Machines placed on pads and foundations, anchored, and leveled to the builder\'s spec.' },
      { k: 'lifts', h: 'Crane &amp; Gantry Picks', p: 'Hydraulic gantries, carry-deck and mobile cranes for planned, documented lifts.' },
      { k: 'low clearance', h: 'Jack, Skid &amp; Skate', p: 'Toe jacks, air skates, roller dollies, and jack-and-slide for moves a crane can\'t reach.' },
      { k: 'planning', h: 'Lift Plans', p: 'Weights, centers of gravity, sling angles, and floor loading worked out before rig day.' },
      { k: 'tight access', h: 'Through the Door', p: 'Machines skated through doorways, up mezzanines, into basements and out of packed floors.' },
      { k: 'staging', h: 'Rig &amp; Stage', p: 'Floor not ready? We receive, secure, and stage the equipment, then set it on your schedule.' },
    ],
  },
  familyGrid: {
    tag: 'every type of rigging',
    h2: 'Every type of rigging we do',
    intro: 'Pick the job closest to yours. Each page covers how that kind of rigging actually gets done — the gear, the planning, and the questions to ask before anyone lifts.',
  },
  sections: [
    {
      tag: 'the long list',
      h2: 'More kinds of rigging we handle',
      paragraphs: [
        'Riggers get called for far more than machine shops. If it\'s heavy, awkward, fragile, or sitting somewhere it was never meant to leave, it\'s a rigging job. A few more we run regularly:',
      ],
      subsections: [
        { h: 'Precision &amp; laboratory equipment', paragraphs: ['Semiconductor tools, electron microscopes, lab instruments, and test stands that can\'t take shock or tilt — moved on air-ride with vibration-conscious handling and set on isolated pads. See <a href="/services/lab-equipment-movers">lab and precision equipment movers</a>.'] },
        { h: 'Printing presses &amp; packaging lines', paragraphs: ['Multi-unit presses, folders, converting and packaging lines broken down in sequence, labeled, moved, and reassembled in order. See <a href="/services/printing-press-movers">printing press movers</a>.'] },
        { h: 'Machinery removal &amp; decommissioning', paragraphs: ['Retired machines, dead lines, and whole plants rigged out safely so the floor can be handed back. See <a href="/services/machinery-removal">machinery removal</a>.'] },
        { h: 'Tanks, vessels &amp; process equipment', paragraphs: ['Storage tanks, pressure vessels, reactors, and skids rigged out of process buildings and set on new saddles or foundations.'] },
        { h: 'Rooftop &amp; crane-in work', paragraphs: ['Rooftop units, cooling towers, and mechanical equipment picked onto roofs and into penthouses, with the lift, the street closure, and the setting planned as one job.'] },
        { h: 'Structural &amp; equipment setting', paragraphs: ['Precast pieces, steel members, modular skids, and enclosures set into place on new construction and plant expansions.'] },
        { h: 'Conveyors, racking &amp; warehouse equipment', paragraphs: ['Conveyor systems, pallet racking, mezzanines, and automation cells removed, relocated, and reinstalled around live operations.'] },
        { h: 'Food, beverage &amp; pharma lines', paragraphs: ['Processing, filling, and packaging lines moved with sanitary handling, sequenced so the new room is ready for validation.'] },
        { h: 'Aerospace, defense &amp; test equipment', paragraphs: ['Autoclaves, test cells, large machining centers, and tooling moved with the documentation and care those programs expect.'] },
      ],
    },
    {
      bg: 'paper',
      tag: 'by the book',
      h2: 'Safe, planned, documented',
      paragraphs: [
        'Every lift runs on a written plan — dimensions, weights, rigging geometry, equipment selection, and sequence settled before anyone touches the load. Our crews work to OSHA rigging and signaling requirements, every piece of rigging hardware is load-rated and inspected before the lift, and floor loading gets checked along the entire path of travel, not just under the pick.',
        'No improvised rigging, no guessing at weights off a brochure, no "we\'ll figure it out on site." If the numbers don\'t work on paper, the lift doesn\'t happen until they do.',
      ],
    },
    {
      tag: 'after the lift',
      h2: 'When the machine has to go somewhere',
      paragraphs: [
        'Plenty of rigging jobs start and end in the same building. The rest need freight: a machine rigged out of one plant, crated, trucked across the country, and set in another. Most companies split that into a rigger on each end and a carrier nobody\'s watching in the middle.',
        'We run it as one project. The same team that rigs the machine out manages the <a href="/services/crating-packing">crating</a>, the load-out, the <a href="/services/dedicated-lanes">transport</a> through our licensed broker and carrier partners, and the rig-in at the destination — one schedule, one point of contact, one crew accountable for the machine the whole way.',
      ],
    },
  ],
  media: {
    tag: 'on the job',
    h2: 'Real rigging, real crews',
    intro: 'Not stock photos of somebody else\'s crane. These are our jobs.',
    checklist: [
      'Machines rigged from the manufacturer\'s lift points — not wherever a strap fits',
      'Sensitive equipment moved with tilt, shock, and vibration monitoring',
      'Tight-access moves through doorways, elevators, mezzanines, and roofs',
      'Floors protected and path of travel load-checked before the move',
      'Every machine set, leveled, and walked with you before we leave',
    ],
    images: [
      { src: '/assets/img/loads/load-mri-rigging.jpg', alt: 'MRI scanner rigged and lifted inside a warehouse by Badass Logistics riggers', caption: 'MRI scanner on the hook — a monitored, planned lift.' },
    ],
  },
  process: {
    h2: 'Our rigging process',
    steps: [
      { h: 'Site &amp; load survey', p: 'Weights, dimensions, center of gravity, doorways, ceilings, and floor capacity — measured, not guessed.' },
      { h: 'Documented lift plan', p: 'Equipment, rigging, sling angles, and sequence specced and signed off before rig day.' },
      { h: 'Prep &amp; coordination', p: 'Lockout/tagout coordination with your team, floor protection, and any permits the site needs.' },
      { h: 'Rig, lift &amp; move', p: 'The crew executes the plan on schedule — nights and weekends when production demands it.' },
      { h: 'Set, level &amp; sign-off', p: 'Placed, anchored, and leveled to spec, then we walk it with you before we call it done.' },
    ],
  },
  industries: {
    h2: 'Industries we rig for',
    items: ['Manufacturing &amp; machine shops', 'Automotive &amp; tool-and-die', 'Hospitals &amp; imaging centers', 'Data centers', 'Energy &amp; utilities', 'Food &amp; beverage', 'Pharma &amp; biotech', 'Semiconductor', 'Aerospace &amp; defense', 'Printing &amp; packaging', 'Plastics &amp; injection molding', 'Commercial construction', 'Warehousing &amp; distribution', 'Universities &amp; labs'],
  },
  faq: [
    { q: 'What is industrial rigging?', a: 'It\'s the planning and physical work of lifting, moving, and setting heavy equipment — using cranes, gantries, jacks, skates, and slings to relocate loads safely and precisely, often into tight or elevated spaces.' },
    { q: 'What types of rigging do you do?', a: 'Every kind: <a href="/services/machinery-moving">machinery moving</a>, <a href="/services/plant-relocation">factory relocation</a>, <a href="/services/machinery-removal">machinery removal</a>, <a href="/services/mri-medical-equipment-rigging">MRI and medical equipment</a>, <a href="/services/lab-equipment-movers">lab equipment</a>, <a href="/services/printing-press-movers">printing presses</a>, <a href="/services/crane-services">crane lifts</a>, <a href="/services/heavy-lift-rigging">jacking and skidding</a>, <a href="/services/millwright-services">millwright installation</a>, <a href="/services/data-center-rigging">data center</a>, <a href="/services/hvac-chiller-rigging">chiller and HVAC</a>, and <a href="/services/transformer-generator-rigging">transformer and generator</a> rigging — plus lab, press, tank, and rooftop work.' },
    { q: 'How heavy a load can you rig?', a: 'From a single crate to machinery over 200,000 lbs. Every lift is matched to load-rated rigging and the right equipment for the weight, the dimensions, and the site.' },
    { q: 'Can you move the equipment to another facility too?', a: 'Yes. We manage it as <a href="/services/project-freight">project freight</a> — crating, loading, transport through our licensed broker and carrier partners, and rig-in at the destination — so one team owns the machine the whole way.' },
    { q: 'Do you work nights and weekends?', a: 'Yes. Most rigging is scheduled around production, so off-shift and weekend moves are normal for us.' },
    { q: 'Do you cover my area?', a: 'We run rigging from 88 locations and cover all 50 states. <a href="/locations">See locations →</a>' },
  ],
  faqTitle: 'Rigging FAQ',
  guides: [
    ['types-of-rigging', 'Types of Rigging: Every Kind, Explained'],
    ['what-is-industrial-rigging', 'What Is Industrial Rigging?'],
    ['how-to-move-a-cnc-machine', 'How to Move a CNC Machine'],
    ['machine-leveling-and-alignment', 'Machine Leveling &amp; Alignment After a Move'],
  ],
  metrosSentinel: 'RIG_METROS',
  metrosTag: 'riggers by metro',
  metrosH2: 'Where we rig',
  metrosIntro: 'Local industrial rigging in the country\'s biggest manufacturing and industrial markets — our own crews and rigging gear, backed by a nationwide network of 88 locations.',
  ctaBand: { h2: 'Got something that needs rigging?', p: 'Send us the equipment and the site. We\'ll plan the pick and quote it fast.' },
};
