/* ===========================================================
   Badass Logistics — build-failing guardrails for a 1,250-page site

   WHY THESE EXIST (seo/schedule.md, run 1, 2026-09-22):
   The verify block in build.js was written when the site was ~660 pages
   and every page had been looked at by a person. The Oct plan roughly
   doubles that, almost entirely from generators. At that size the
   failure modes change: nobody reads 500 new pages, so a defect in one
   SERVICES{} block ships 88 times before anyone notices. "Heavy
   Equipment Moving" survived on 88 city page titles after the service
   was retired precisely because check-content.js only ever looked at
   content/services.

   These five are deliberately build-FAILING, not warnings. They are
   what makes publishing at volume safe; a warning at this scale is a
   thing nobody reads.

   Each export takes the shared context from build.js's verify() and
   calls check(ok, msg, detail) — which prints and counts failures.
   =========================================================== */
const fs = require('fs');
const path = require('path');

// Services whose city matrix is generated by build-service-cities.js.
const MATRIX_SERVICES = ['machinery-moving', 'rigging', 'cnc-machine-movers', 'plant-relocation'];

// Hard ceilings. These are not the plan — they are the blast radius. The
// Oct 2026 plan lands 853 matrix pages and 31 dispatch pages; these sit
// above that so a fat-fingered WAVES{} entry or a duplicated EQUIPMENT
// block fails the build instead of publishing a few thousand pages.
const MATRIX_HARD_CAP = 1000;
const DISPATCH_HARD_CAP = 40;

// Every service × city page has to carry at least this many DISTINCT
// real local tokens — the city, its state, its suburbs and counties, its
// Interstates. Below this the page is a template with a city name
// find-replaced into it, which is what put machinery-moving/omaha-ne at
// position 67 ranking for four other cities.
const LOCAL_TOKEN_FLOOR = 6;

const stateSlug = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-');

// Visible text with tag boundaries preserved as spaces, so two adjacent
// <span>s don't concatenate into a word that was never on the page.
function visibleText(html) {
  return html
    .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, ' ')
    .replace(/<!--[\s\S]*?-->/g, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&amp;/g, '&').replace(/&nbsp;/g, ' ').replace(/&#39;|&rsquo;/g, "'")
    .replace(/\s+/g, ' ')
    .trim();
}

/* -----------------------------------------------------------
   1. NO SUB-CITY URLs
   Suburbs belong in the coverage table on the city page and nowhere
   else. The matrix never gets a URL below city level — that is how a
   programmatic site goes from 850 useful pages to 8,500 thin ones.
   Enforced structurally: every file in a matrix service directory must
   be a known city slug or a known state-hub slug. Nothing else.
   ----------------------------------------------------------- */
function noSubCityUrls({ ROOT, locations, STATE_NAMES, check }) {
  const citySlugs = new Set(locations.map(l => `${l.city.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}-${l.state.toLowerCase()}`));
  const stateSlugs = new Set(Object.values(STATE_NAMES).map(stateSlug));
  const bad = [];
  for (const svc of MATRIX_SERVICES) {
    const dir = path.join(ROOT, 'services', svc);
    if (!fs.existsSync(dir)) continue;
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      if (e.isDirectory()) { bad.push(`/services/${svc}/${e.name}/ — a directory under a matrix service means a URL below city level`); continue; }
      if (!e.name.endsWith('.html')) continue;
      const slug = e.name.replace(/\.html$/, '');
      if (citySlugs.has(slug) || stateSlugs.has(slug)) continue;
      bad.push(`/services/${svc}/${slug} — not a known city or state slug (sub-city page?)`);
    }
  }
  check(bad.length === 0, `no sub-city URLs: ${MATRIX_SERVICES.length} matrix services scanned`, bad);
}

/* -----------------------------------------------------------
   2. NO DISPATCH GEO URLs — ever
   Dispatch is not a local service. A fleet's trucks run wherever the
   freight goes, so a page promising dispatch in one metro is telling a
   fleet owner something untrue about their own business. The dispatch
   pages are organised by EQUIPMENT for exactly this reason.
   ----------------------------------------------------------- */
function noDispatchGeo({ ROOT, locations, STATE_NAMES, check }) {
  const cityWords = new Set(locations.map(l => l.city.toLowerCase().replace(/[^a-z0-9]+/g, '-')));
  const stateSlugs = new Set(Object.values(STATE_NAMES).map(stateSlug));
  const stateCodes = new Set(Object.keys(STATE_NAMES).map(s => s.toLowerCase()));
  const bad = [];

  const scan = (dirRel) => {
    const dir = path.join(ROOT, dirRel);
    if (!fs.existsSync(dir)) return;
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      if (e.isDirectory()) { bad.push(`/${dirRel}/${e.name}/ — no nested directories under dispatch`); continue; }
      if (!e.name.endsWith('.html')) continue;
      const slug = e.name.replace(/\.html$/, '');
      const tail = slug.split('-').pop();
      if (stateCodes.has(tail)) bad.push(`/${dirRel}/${slug} — ends in a state code`);
      else if (stateSlugs.has(slug)) bad.push(`/${dirRel}/${slug} — is a state slug`);
      else if (cityWords.has(slug)) bad.push(`/${dirRel}/${slug} — is a city name`);
    }
  };
  scan('services/truck-dispatch');
  scan('services/dispatching');

  // A geo-shaped <title> is the same mistake wearing a different URL.
  const dir = path.join(ROOT, 'services/truck-dispatch');
  if (fs.existsSync(dir)) {
    for (const n of fs.readdirSync(dir).filter(f => f.endsWith('.html'))) {
      const html = fs.readFileSync(path.join(dir, n), 'utf8');
      if (html.includes('<!--REDIRECT-->')) continue;
      const t = (html.match(/<title>([\s\S]*?)<\/title>/) || [, ''])[1];
      for (const l of locations) {
        if (new RegExp(`\\b${l.city.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')},?\\s+${l.state}\\b`, 'i').test(t)) {
          bad.push(`/services/truck-dispatch/${n.replace(/\.html$/, '')} — geo-targeted title: "${t.trim()}"`);
          break;
        }
      }
    }
  }
  check(bad.length === 0, `no dispatch geo URLs or geo titles`, bad);
}

/* -----------------------------------------------------------
   3. UNIQUENESS FLOOR on the city matrix
   Counts DISTINCT real local tokens per page: the city, its state, the
   suburbs and counties from locations.json, and the state's Interstates.
   A page that clears this is not automatically good — but a page that
   fails it is definitely a template with a name swapped in.
   ----------------------------------------------------------- */
function matrixUniquenessFloor({ ROOT, locations, STATE_NAMES, interstatesOf, check }) {
  const byKey = {};
  locations.forEach(l => { byKey[`${l.city.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}-${l.state.toLowerCase()}`] = l; });
  const thin = [];
  let scanned = 0, worst = { n: Infinity, url: '' };

  for (const svc of MATRIX_SERVICES) {
    const dir = path.join(ROOT, 'services', svc);
    if (!fs.existsSync(dir)) continue;
    for (const n of fs.readdirSync(dir).filter(f => f.endsWith('.html'))) {
      const loc = byKey[n.replace(/\.html$/, '')];
      if (!loc) continue;                       // state hubs are checked elsewhere
      const text = visibleText(fs.readFileSync(path.join(dir, n), 'utf8'));
      const tokens = new Set();
      const want = [loc.city, STATE_NAMES[loc.state] || loc.state]
        .concat((loc.near || []).map(x => x.name))
        .concat((loc.near || []).map(x => x.county).filter(Boolean))
        .concat(String(interstatesOf(loc.state)).split(/[,\s]+and\s+|,\s*/).map(s => s.trim()).filter(x => /^I-\d/.test(x)));
      for (const w of want) if (w && w.length > 2 && text.includes(w)) tokens.add(w);
      scanned++;
      if (tokens.size < worst.n) worst = { n: tokens.size, url: `/services/${svc}/${n.replace(/\.html$/, '')}` };
      if (tokens.size < LOCAL_TOKEN_FLOOR) thin.push(`/services/${svc}/${n.replace(/\.html$/, '')} — only ${tokens.size} local tokens (floor ${LOCAL_TOKEN_FLOOR})`);
    }
  }
  check(thin.length === 0, `matrix uniqueness floor: ${scanned} city pages, thinnest ${worst.n} local tokens (${worst.url})`, thin);
}

/* -----------------------------------------------------------
   4. MATRIX CAP
   Pages on disk must match what the generators say they built, and
   neither may exceed its hard ceiling. Catches a WAVES{} entry pointing
   at the wrong key list, a generator half-failing, and stale pages left
   behind when a service is pulled out of a wave.
   ----------------------------------------------------------- */
function matrixCap({ ROOT, locations, STATE_NAMES, check }) {
  const bad = [];
  const citySlugs = new Set(locations.map(l => `${l.city.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')}-${l.state.toLowerCase()}`));

  const manifestPath = path.join(ROOT, 'data/service-cities.json');
  if (!fs.existsSync(manifestPath)) bad.push('data/service-cities.json is missing — the matrix generator did not finish');
  else {
    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
    const declared = {};
    manifest.forEach(m => { declared[m.service] = (declared[m.service] || 0) + 1; });
    for (const svc of new Set([...MATRIX_SERVICES, ...Object.keys(declared)])) {
      const dir = path.join(ROOT, 'services', svc);
      const onDisk = fs.existsSync(dir)
        ? fs.readdirSync(dir).filter(f => f.endsWith('.html') && citySlugs.has(f.replace(/\.html$/, ''))).length : 0;
      const want = declared[svc] || 0;
      if (onDisk !== want) bad.push(`${svc}: ${onDisk} city pages on disk, generator declared ${want}`);
    }
    if (manifest.length > MATRIX_HARD_CAP) bad.push(`matrix is ${manifest.length} pages, hard cap is ${MATRIX_HARD_CAP} — raise the cap deliberately or fix the wave`);
  }

  const dispatchPath = path.join(ROOT, 'data/dispatch-equipment.json');
  if (fs.existsSync(dispatchPath)) {
    const d = JSON.parse(fs.readFileSync(dispatchPath, 'utf8'));
    const dir = path.join(ROOT, 'services/truck-dispatch');
    const onDisk = fs.existsSync(dir) ? fs.readdirSync(dir).filter(f => f.endsWith('.html')).length : 0;
    if (onDisk !== d.count + 1) bad.push(`dispatch: ${onDisk} pages on disk, generator declared ${d.count} + 1 hub`);
    if (onDisk > DISPATCH_HARD_CAP) bad.push(`dispatch is ${onDisk} pages, hard cap is ${DISPATCH_HARD_CAP}`);
  }
  check(bad.length === 0, `matrix + dispatch counts match their generators and stay under cap`, bad);
}

/* -----------------------------------------------------------
   5. POSITIONING LINT ON GENERATOR OUTPUT
   check-content.js only reads content/services, and check 5 in build.js
   only reads titles, descriptions and chrome. Neither would have caught
   a retired service name in the BODY of 88 generated pages — which is
   exactly how "Heavy Equipment Moving" survived the revamp.

   Disclaimer-aware, like check 8: the dispatch pages have to SAY
   "permitted oversize" in order to refuse it, and refusing it is the
   point. A sentence carrying a negation or retirement marker is exempt;
   a sentence that reads as an offer is not.
   ----------------------------------------------------------- */
const RETIRED = /\b(heavy[- ]haul|heavy equipment mover|heavy equipment moving|heavy machinery mover|heavy machinery moving|oversize|over[- ]dimensional|superload|escort vehicle|pilot car|permitted load|permit load|service area)\b/i;
const DISCLAIMER = /\b(not|no|nor|never|don't|doesn't|cannot|can't|outside|retired|previously|longer|without|declines?|declined|refuses?|refuse)\b/i;

// An FAQ question is not an offer — "Do you dispatch oversize loads?" is
// a heading whose answer sits in the next sentence. So a question clears
// only if the sentence AFTER it carries the denial. "Do you dispatch
// oversize loads? Yes, we do." still fails, which is the point.

function generatorPositioning({ ROOT, check }) {
  const dirs = ['services/truck-dispatch', 'locations', ...MATRIX_SERVICES.map(s => `services/${s}`)];
  const bad = [];
  let scanned = 0;
  for (const rel of dirs) {
    const dir = path.join(ROOT, rel);
    if (!fs.existsSync(dir)) continue;
    for (const n of fs.readdirSync(dir).filter(f => f.endsWith('.html'))) {
      const html = fs.readFileSync(path.join(dir, n), 'utf8');
      if (html.includes('<!--REDIRECT-->')) continue;
      scanned++;
      // Chrome is identical on every page and is covered by check 5 —
      // strip it so one footer wording can't report 600 failures.
      const body = html.replace(/<div class="topbar">[\s\S]*?<\/header>/, ' ').replace(/<footer[\s>][\s\S]*?<\/footer>/, ' ');
      const sentences = visibleText(body).split(/(?<=[.!?])\s+|\s*[|·]\s*/);
      for (let i = 0; i < sentences.length; i++) {
        const sentence = sentences[i];
        const m = sentence.match(RETIRED);
        const answered = sentence.trim().endsWith('?') && DISCLAIMER.test(sentences[i + 1] || '');
        if (m && !DISCLAIMER.test(sentence) && !answered) {
          bad.push(`/${rel}/${n.replace(/\.html$/, '')} — "${m[0]}" in: ${sentence.slice(0, 100)}`);
          break;
        }
      }
    }
  }
  check(bad.length === 0, `positioning lint on generator output: ${scanned} generated pages`, bad);
}

module.exports = {
  MATRIX_SERVICES, MATRIX_HARD_CAP, DISPATCH_HARD_CAP, LOCAL_TOKEN_FLOOR,
  noSubCityUrls, noDispatchGeo, matrixUniquenessFloor, matrixCap, generatorPositioning,
};
